# Define the type of the connection
mechanism_type: "Cable" 

# Define the total number of robots
num_of_robots: 1

# Define where the cable is attached at
rho: 
  - {x: 0.0, y: 0.0, z: 0.0}

# Define the cable length
cable_length: [0.5]

# Define the types of robots attach to the payload
robot_list: ["snapdragonfly"]
