# payload inertia parameters
mass: 0.104
inertia: {Ixx: 0.004053, Ixy: 0.0, Ixz: 0.0, Iyx: 0.0, Iyy: 0.000013225, Iyz: 0.0, Izx: 0.0, Izy: 0.0, Izz: 0.004053}

# path to payload mesh
mesh_path: "package://rotor_tm/mesh/long_bar.STL"
